FROM node:21-alpine3.18

WORKDIR /app

COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src

RUN ls -a
RUN npm install -g npm@latest && npm install -g nodemon
RUN npm install

EXPOSE 4000

CMD [ "npm", "run", "dev" ]
