FROM node:21-alpine3.18

WORKDIR /app

COPY package.json package-lock.json ./
COPY tsconfig.json ./
COPY .npmrc ./

RUN ls -a
RUN npm install -g npm@latest && npm install -g nodemon
RUN npm install

ENV NODE_ENV=development
RUN npm install --production=false

COPY src ./src

RUN ls -a

EXPOSE 4002

CMD ["npm", "run", "dev"]
